src/AppBundle/Entity/News.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\UploadedDocuments\HasUploadedDocumentsInterface;
use AppBundle\Entity\UploadedDocuments\HasUploadedDocumentsTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * News
 *
 * @ORM\Table(name="news")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\NewsRepository")
 */
class News implements EntityInterface, HasImageInterface, TimestampableInterface, HasUploadedDocumentsInterface
{
    use ORMBehaviors\Translatable\Translatable;
    use Moderatable;
    use Timestampable;
    use HasUploadedDocumentsTrait;

    CONST STATUS_DRAFT = 1;
    CONST STATUS_MODERATING = 2;
    CONST STATUS_PUBLISHED = 3;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var NewsType
     * @ORM\ManyToOne(targetEntity="NewsType")
     */
    private $type;

    /**
     * @var Rubric
     * @ORM\ManyToOne(targetEntity="Rubric")
     */
    private $rubric;

    /**
     * @ORM\ManyToMany(targetEntity="Keyword", cascade={"persist"})
     */
    private $keywords;

    /**
     * @var int
     * @ORM\Column(name="status", type="integer", nullable=false, options={"default" = 1})
     */
    private $status;

    /**
     * @var University
     * @ORM\ManyToOne(targetEntity="University")
     */
    private $university;

    /**
     * @var \DateTime
     * @ORM\Column(name="published_at", type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @var bool
     * @ORM\Column(name="is_important", type="boolean", nullable=false, options={"default" = false})
     */
    private $isImportant;

    /**
     * @var \AppBundle\Entity\Image
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Image", cascade={"persist", "refresh", "remove"})
     * @ORM\JoinColumn(name="image_id", referencedColumnName="id", onDelete="SET NULL")
     */
    private $image;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->keywords = new \Doctrine\Common\Collections\ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->uploadedDocuments = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Set publishedAt
     *
     * @param \DateTime $publishedAt
     *
     * @return News
     */
    public function setPublishedAt($publishedAt)
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    /**
     * Get publishedAt
     *
     * @return \DateTime
     */
    public function getPublishedAt()
    {
        return $this->publishedAt;
    }

    /**
     * Add keyword
     *
     * @param \AppBundle\Entity\Keyword $keyword
     *
     * @return News
     */
    public function addKeyword(\AppBundle\Entity\Keyword $keyword)
    {
        $this->keywords[] = $keyword;

        return $this;
    }

    /**
     * Remove keyword
     *
     * @param \AppBundle\Entity\Keyword $keyword
     */
    public function removeKeyword(\AppBundle\Entity\Keyword $keyword)
    {
        $this->keywords->removeElement($keyword);
    }

    /**
     * Get keywords
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * Set isImportant
     *
     * @param boolean $isImportant
     *
     * @return News
     */
    public function setIsImportant($isImportant)
    {
        $this->isImportant = $isImportant;

        return $this;
    }

    /**
     * Get isImportant
     *
     * @return boolean
     */
    public function getIsImportant()
    {
        return $this->isImportant;
    }

    /**
     * Set type
     *
     * @param \AppBundle\Entity\NewsType $type
     *
     * @return News
     */
    public function setType(\AppBundle\Entity\NewsType $type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return \AppBundle\Entity\NewsType
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set rubric
     *
     * @param \AppBundle\Entity\Rubric $rubric
     *
     * @return News
     */
    public function setRubric(\AppBundle\Entity\Rubric $rubric = null)
    {
        $this->rubric = $rubric;

        return $this;
    }

    /**
     * Get rubric
     *
     * @return \AppBundle\Entity\Rubric
     */
    public function getRubric()
    {
        return $this->rubric;
    }

    /**
     * Set university
     *
     * @param \AppBundle\Entity\University $university
     *
     * @return News
     */
    public function setUniversity(\AppBundle\Entity\University $university = null)
    {
        $this->university = $university;

        return $this;
    }

    /**
     * Get university
     *
     * @return \AppBundle\Entity\University
     */
    public function getUniversity()
    {
        return $this->university;
    }

    /**
     * Set image
     *
     * @param \AppBundle\Entity\Image $image
     *
     * @return News
     */
    public function setImage(\AppBundle\Entity\Image $image = null)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return \AppBundle\Entity\Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return string
     */
    public function getImagePath()
    {
        return '/images/'.$this->image->getFileName();
    }

    /**
     * @return string
     */
    public function getImageFolder()
    {
        return 'news';
    }
}

src/AppBundle/Form/StaticPage/HighlightType.php
<?php

namespace AppBundle\Form\StaticPage;

use Symfony\Component\Form\{AbstractType, FormBuilderInterface};
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class HighlightType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('number', null, [
            'label' => 'static.highlights.number',
            'translation_domain' => 'dictionary',
        ])
        ->add('description', TextareaType::class, [
            'label' => 'static.highlights.description',
            'translation_domain' => 'dictionary',
        ])
        ->add('delete', ButtonType::class, [
            'attr' => [
                'class' => 'highlight-delete pink-button default-button btn ladda-button',
            ],
            'label' => 'static.highlights.delete',
            'translation_domain' => 'dictionary',
        ]);
    }
}

src/AppBundle/Controller/StaticPageController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\AcademicMobilityType;
use AppBundle\Entity\Audience;
use AppBundle\Entity\ContestType;
use AppBundle\Service\StaticCounter;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

class StaticPageController extends Controller
{
    /**
     * @var StaticCounter
     */
    private $staticCounter;

    /**
     * StaticPageController constructor.
     * @param StaticCounter $staticCounter
     */
    public function __construct(StaticCounter $staticCounter)
    {
        $this->staticCounter = $staticCounter;
    }

    /**
     * @Route(
     *     path="/{_locale}/students/",
     *     name="main.static.students",
     *     requirements={"_locale": "%route.available_locales%"}
     * )
     */
    public function studentsAction()
    {
        $viewTypes = [
            ContestType::CONTEST_NAME__NIOKR => [
                'type' => StaticCounter::TYPE_CONTEST,
                'data' => [ContestType::CONTEST_TYPE__NIOKR],
                'audience' => [
                    Audience::AUDIENCE_TYPE__BACHELORS,
                    Audience::AUDIENCE_TYPE__MASTERS,
                ],
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SCHOOLS => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SCHOOLS],
                'audience' => [
                    Audience::AUDIENCE_TYPE__BACHELORS,
                    Audience::AUDIENCE_TYPE__MASTERS,
                ],
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE],
                'audience' => [
                    Audience::AUDIENCE_TYPE__BACHELORS,
                    Audience::AUDIENCE_TYPE__MASTERS,
                ],
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [
                    AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE,
                    AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__MASTERCLASS,
                ],
                'audience' => [
                    Audience::AUDIENCE_TYPE__BACHELORS,
                    Audience::AUDIENCE_TYPE__MASTERS,
                ],
            ],
        ];

        $counterData = $this->staticCounter
            ->getCountersByTypes($viewTypes);

        $views = [
            ContestType::CONTEST_NAME__NIOKR => [
                'translate' => 'middle-menu.rd',
                'count' => $counterData[ContestType::CONTEST_NAME__NIOKR],
                'link' => $this->generateUrl('main.contest.list', [
                    'audience' => Audience::AUDIENCE_MAP[Audience::AUDIENCE_TYPE__BACHELORS],
                    'contestType' => ContestType::CONTEST_TYPE_MAP[ContestType::CONTEST_TYPE__NIOKR]
                ])
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SCHOOLS => [
                'translate' => 'middle-menu.summerschools',
                'count' => $counterData[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SCHOOLS],
                'link' => $this->generateUrl('main.academic_mobility.list', [
                    'audiences' => Audience::AUDIENCE_MAP[Audience::AUDIENCE_TYPE__BACHELORS],
                    'mobilityType' => AcademicMobilityType::ACADEMIC_MOBILITY_MAP[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SCHOOLS]
                ])
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE => [
                'translate' => 'middle-menu.conferences',
                'count' => $counterData[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE],
                'link' => $this->generateUrl('main.academic_mobility.list', [
                    'audiences' => Audience::AUDIENCE_MAP[Audience::AUDIENCE_TYPE__BACHELORS],
                    'mobilityType' => AcademicMobilityType::ACADEMIC_MOBILITY_MAP[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE]
                ])
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE => [
                'translate' => 'middle-menu.lectures_class',
                'count' => $counterData[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE],
                'link' => $this->generateUrl('main.academic_mobility.list', [
                    'audiences' => Audience::AUDIENCE_MAP[Audience::AUDIENCE_TYPE__BACHELORS],
                    'mobilityType' => AcademicMobilityType::ACADEMIC_MOBILITY_MAP[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE]
                ])
            ],
        ];

        return $this->render('AppBundle:StaticPage:students.html.twig', ['views' => $views]);
    }

    /**
     * @Route(
     *     path="/{_locale}/undergraduate/",
     *     name="main.static.scholar",
     *     requirements={"_locale": "%route.available_locales%"}
     * )
     */
    public function scholarAction()
    {

        // Интересующие типы
        $viewTypes = [
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SEMINAR => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [
                    AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SEMINAR,
                    AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__MASTERCLASS
                ],
                'audience' => [Audience::AUDIENCE_TYPE__SCHOLAR],
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE],
                'audience' => [Audience::AUDIENCE_TYPE__SCHOLAR],
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE],
                'audience' => [Audience::AUDIENCE_TYPE__SCHOLAR],
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__ONLINE => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__ONLINE],
                'audience' => [Audience::AUDIENCE_TYPE__SCHOLAR],
            ],
        ];

        $counterData = $this->staticCounter
            ->getCountersByTypes($viewTypes);

        $views = [
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SEMINAR => [
                'translate' => 'middle-menu.seminars',
                'count' => $counterData[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SEMINAR],
                'link' => $this->generateUrl('main.academic_mobility.list', [
                    'audiences' => Audience::AUDIENCE_MAP[Audience::AUDIENCE_TYPE__SCHOLAR],
                    'mobilityType' => AcademicMobilityType::ACADEMIC_MOBILITY_MAP[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__SEMINAR]
                ])
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE => [
                'translate' => 'middle-menu.conferences',
                'count' => $counterData[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE],
                'link' => $this->generateUrl('main.academic_mobility.list', [
                    'audiences' => Audience::AUDIENCE_MAP[Audience::AUDIENCE_TYPE__SCHOLAR],
                    'mobilityType' => AcademicMobilityType::ACADEMIC_MOBILITY_MAP[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE]
                ])
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE => [
                'translate' => 'middle-menu.lectures-meetings',
                'count' => $counterData[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE],
                'link' => $this->generateUrl('main.academic_mobility.list', [
                    'audiences' => Audience::AUDIENCE_MAP[Audience::AUDIENCE_TYPE__SCHOLAR],
                    'mobilityType' => AcademicMobilityType::ACADEMIC_MOBILITY_MAP[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE]
                ])
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__ONLINE => [
                'translate' => 'middle-menu.webinars',
                'count' => $counterData[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__ONLINE],
                'link' => $this->generateUrl('main.academic_mobility.list', [
                    'audiences' => Audience::AUDIENCE_MAP[Audience::AUDIENCE_TYPE__SCHOLAR],
                    'mobilityType' => AcademicMobilityType::ACADEMIC_MOBILITY_MAP[AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__ONLINE]
                ])
            ],
        ];

        return $this->render('AppBundle:StaticPage:scholar.html.twig', ['views' => $views]);
    }

    /**
     * @Route(
     *     path="/{_locale}/scientist/",
     *     name="main.static.scientist",
     *     requirements={"_locale": "%route.available_locales%"}
     * )
     */
    public function scientistAction()
    {

        $viewTypes = [
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__CONFERENCE],
                'audience' => [Audience::AUDIENCE_TYPE__RESEARCHERS],
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE => [
                'type' => StaticCounter::TYPE_ACADEMIC,
                'data' => [AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__LECTURE],
                'audience' => [Audience::AUDIENCE_TYPE__RESEARCHERS],
            ],
            AcademicMobilityType::ACADEMIC_MOBILITY_TYPE__TRAINING => [

src/AppBundle/Resources/views/StaticPage/about.html.twig
{% extends '@App/base.html.twig' %}

{% block header %}
    {% include "AppBundle::header.html.twig" %}
{% endblock %}

{% set body_class = 'default-page members-page tinted' %}

{% block footer %}
    {% include 'AppBundle::footer.html.twig' %}
{% endblock %}

{% set data = static_data('about') %}

{% block body %}
    <main>
        <section class="title-wrapper">
            <div class="container">
                <h1 class="default-title">
                    {{ 'middle-menu.association-about' | trans }}
                </h1>
            </div>
        </section>
        <section class="content">
            <div class="container clearfix">
                <div class="row">
                    <div class="col-md-2 about-asso-info">

                        <img class="news-show-logo"
                             src="{{ data.translate().image ? data.translate().imagePath : asset('bundles/app/css/img/logo-blue.png') }}"
                             alt=""/>

                        {{ data.translate().leftBlock|raw }}

                    </div>
                    <div class="col-md-7 about-asso practice-content">
                        {{ data.translate().text|raw }}
                        {% for file in data.uploadedDocuments %}
                            <a href="{{ path('download.document', {id: file.id}) }}" target="_blank" class="download-link">
                                {{ file.downloadName }} <span>{{ file.formattedBytes }}</span>
                            </a>
                        {% endfor %}
                    </div>
                    <div class="col-sm-3">
                        {% include '@App/default/News/association_news.html.twig' %}
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

src/AppBundle/Resources/views/StaticPage/council.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block header %}
    {% include "AppBundle::header.html.twig" %}
{% endblock %}

{% block body_class %}default-page council-page tinted{% endblock %}

{% block footer %}
    {% include 'AppBundle::footer.html.twig' %}
{% endblock %}

{% block body %}
    <main>
        <section class="title-wrapper">
            <div class="container">
                <h1 class="default-title">
                    {{ 'middle-menu.association-council' | trans }}
                </h1>
            </div>
        </section>
        <section class="content">
            <div class="container">
                {% set data = static_data('council') %}
                <div class="content-text">
                    {{ data.translate().text|raw }}
                </div>
                <div class="row clearfix">
                    <div class="col-sm-6">
                        <div class="person-item">
                            <div class="clearfix">
                                {% set chairman = personality('chairman', 1) %}
                                <a href="{{ chairman.link ?? 'javascript:void(0)' }}" class="{{ chairman.image ? '' : 'person-ico-default' }}">
                                    <img src="{{ chairman.imagePath }}" class="person-ico" alt=""/>
                                </a>
                                <div class="pull-left">
                                    <p class="default-label">{{ chairman.associationPosition.transKey|trans([], 'dictionary') }}</p>
                                    <h3><a href="{{ chairman.link ?? 'javascript:void(0)' }}">{{ chairman.fullName }}</a></h3>
                                    <p>{{ chairman.professionalPosition }}</p>
                                    <p><a href="{{ chairman.workPlace.translate().url }}">{{ chairman.workPlace }}</a></p>
                                </div>
                            </div>
                            <div class="person-addition-info">
                                {{ data.translate().competenceOfChairman|raw }}
                            </div>
                            <button class="default-button show-info" data-text="{{ 'hide' | trans }} {{ 'competences' | trans }}">{{ 'show' | trans }} {{ 'competences' | trans }}</button>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="person-item">
                            {% set executive = personality('executive', 1) %}
                            <div class="clearfix">
                                <a href="{{ executive.link ?? 'javascript:void(0)' }}" class="{{ executive.image ? '' : 'person-ico-default' }}">
                                    <img src="{{ executive.imagePath }}" class="person-ico" alt=""/>
                                </a>
                                <div class="pull-left">
                                    <p class="default-label">{{ executive.associationPosition.transKey|trans([], 'dictionary') }}</p>
                                    <h3><a href="{{ executive.link ?? 'javascript:void(0)' }}">{{ executive.fullName }}</a></h3>
                                    <p>{{ executive.professionalPosition }}</p>
                                    <p><a href="{{ executive.workPlace.translate().url }}">{{ executive.workPlace }}</a></p>
                                </div>
                            </div>
                            <div class="person-addition-info">
                                {{ data.translate().competenceOfExecutive|raw }}
                            </div>
                            <button class="default-button show-info" data-text="{{ 'hide' | trans }} {{ 'competences' | trans }}">{{ 'show' | trans }} {{ 'competences' | trans }}</button>
                        </div>
                    </div>
                </div>
                {% set members = personality('council_member') %}
                <div class="row clearfix">
                    {% for member in members %}
                    <div class="col-sm-6">
                        <div class="person-item">
                            <div class="clearfix">
                                <a href="{{ member.link ?? 'javascript:void(0);' }}" class="{{ member.image ? '' : 'person-ico-default' }}">
                                    <img src="{{ member.imagePath }}" class="person-ico" alt=""/>
                                </a>
                                <div class="pull-left">
                                    <p class="default-label">{{ member.associationPosition.transKey|trans([], 'dictionary') }}</p>
                                    <h3><a href="{{ member.link }}">{{ member.fullName }}</a></h3>
                                    <p>{{ member.professionalPosition }}</p>
                                    <p><a href="{{ member.workPlace.translate().url }}">{{ member.workPlace }}</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% set honoraryMembers = personality('honorary_council_member') %}
                    {% for member in honoraryMembers %}
                        <div class="col-sm-6">
                            <div class="person-item">
                                <div class="clearfix">
                                    <a href="{{ member.link ?? 'javascript:void(0);' }}" class="{{ member.image ? '' : 'person-ico-default' }}">
                                        <img src="{{ member.imagePath }}" class="person-ico" alt=""/>
                                    </a>
                                    <div class="pull-left">
                                        <p class="default-label">{{ member.associationPosition.transKey|trans([], 'dictionary') }}</p>
                                        <h3>
                                            <a href="{{ member.link }}">{{ member.fullName }}</a></h3>
                                        <p>{{ member.professionalPosition }}</p>
                                        <p><a href="{{ member.workPlace.translate().url }}">{{ member.workPlace }}</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

src/AppBundle/Resources/views/StaticPage/members.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block header %}
    {% include "AppBundle::header.html.twig" %}
{% endblock %}

{% block body_class %}default-page members-page tinted{% endblock %}

{% block footer %}
    {% include 'AppBundle::footer.html.twig' %}
{% endblock %}

{% block body %}
    <main>
        <section class="title-wrapper">
            <div class="container">
                <h1 class="default-title">
                    {{ 'middle-menu.association-members' | trans }}
                </h1>
            </div>
        </section>
        <section class="content">
            <div class="container">
                <div class="rubrics rubrics-members clearfix row">
                    {% for university in universities %}
                        <div class="col-lg-4 col-md-6">
                            <a href="{{ path('home.university.index', {'id': university.id}) }}" class="rubrics-item">
                                <p>{{ uni_logo(university) }}</p>
                                <p>{{ university.translate().getFullName() }}</p>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

src/AppBundle/Resources/views/StaticPage/revision_commettee.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block header %}
    {% include "AppBundle::header.html.twig" %}
{% endblock %}

{% block body_class %}default-page council-page tinted{% endblock %}

{% block footer %}
    {% include 'AppBundle::footer.html.twig' %}
{% endblock %}

{% block body %}
    <main>
        <section class="title-wrapper">
            <div class="container">
                <h1 class="default-title">
                    {{ 'middle-menu.audit-cometee' | trans }}
                </h1>
            </div>
        </section>
        <section class="content">
            <div class="container">
                {% set data = static_data('commettee') %}
                <div class="content-text">
                    {{ data.translate().text | raw }}
                </div>
                {% set chairman = personality('revision_commettee_chairman', 1) %}
                {% set members = personality('revision_commettee_member') %}
                {% set members = [chairman]|merge(members) %}

                <div class="row clearfix">
                {% for member in members %}
                    <div class="col-sm-6">
                        <div class="person-item">
                            <div class="clearfix">
                                <a href="{{ member.link ?? 'javascript:void(0);' }}" class="{{ member.image ? '' : 'person-ico-default' }}">
                                    <img src="{{ member.imagePath }}" class="person-ico" alt="" />
                                </a>
                                <div class="pull-left">
                                    <p class="default-label">{{ member.associationPosition|trans([], 'dictionary') }}</p>
                                    <h3><a href="{{ member.link }}">{{ member.fullName }}</a></h3>
                                    <p>{{ member.professionalPosition }}</p>
                                    <p><a href="{{ member.workPlace.translate().url }}">{{ member.workPlace }}</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </section>
    </main>
{% endblock %}

src/AppBundle/Resources/views/StaticPage/rubric_item.html.twig
<div class="rubrics-item">
    <span class="rubric-counter">{{ view['count'] }}</span>
    {% if view['link'] != false %}
        <a href="{{ view['link'] }}"
           class="rubric-title">{{ view['translate']|trans }}</a>
    {% else %}
        <span class="rubric-title">{{ view['translate']|trans }}</span>
    {% endif %}

</div>