src/AppBundle/Entity/University.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\UploadedDocuments\HasUploadedDocumentsInterface;
use AppBundle\Entity\UploadedDocuments\HasUploadedDocumentsTrait;
use AppBundle\Extension\Doctrine\Point;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * University
 *
 * @ORM\Table(name="university")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UniversityRepository")
 */
class University implements EntityInterface, HasUploadedDocumentsInterface
{
    use ORMBehaviors\Translatable\Translatable;
    use HasUploadedDocumentsTrait;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\UniversityBranch")
     */
    private $mainBranch;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\UniversityBranch", mappedBy="university")
     */
    private $branches;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Partner", inversedBy="universities")
     */
    private $partners;

    /**
     * @var SliderData
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\SliderData", inversedBy="university", cascade={"persist"})
     */
    private $sliderData;

    /**
     * @var string
     *
     * @ORM\Column(name="logo", type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @var string
     *
     * @ORM\Column(name="photo", type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\SocialLinks", cascade={"persist"})
     */
    private $socialLinks;

    /**
     * @ORM\Column(type="point", nullable=true)
     *
     * @var Point
     */
    private $locationPoint;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->branches = new \Doctrine\Common\Collections\ArrayCollection();
        $this->partners = new \Doctrine\Common\Collections\ArrayCollection();
        $this->uploadedDocuments = new ArrayCollection();
    }

    public function __toString()
    {
        return (string) $this->translate()->getName();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set logo
     *
     * @param string $logo
     *
     * @return University
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Set mainBranch
     *
     * @param \AppBundle\Entity\UniversityBranch $mainBranch
     *
     * @return University
     */
    public function setMainBranch(\AppBundle\Entity\UniversityBranch $mainBranch = null)
    {
        $this->mainBranch = $mainBranch;

        return $this;
    }

    /**
     * Get mainBranch
     *
     * @return \AppBundle\Entity\UniversityBranch
     */
    public function getMainBranch()
    {
        return $this->mainBranch;
    }

    public function getSubBranches()
    {
        $mainBranch = $this->mainBranch;
        return $this->branches->filter(function ($branch) use ($mainBranch) {
            return $branch !== $mainBranch;
        });
    }

    public function addSubBranch(UniversityBranch $branch)
    {
        $this->addBranch($branch);

        return $this;
    }

    public function removeSubBranch(UniversityBranch $branch)
    {
        if (!$branch->isMainBranch()) {
            $this->removeBranch($branch);
        }

        return $this;
    }

    /**
     * Add branch
     *
     * @param \AppBundle\Entity\UniversityBranch $branch
     *
     * @return University
     */
    public function addBranch(\AppBundle\Entity\UniversityBranch $branch)
    {
        $this->branches[] = $branch;

        return $this;
    }

    /**
     * Remove branch
     *
     * @param \AppBundle\Entity\UniversityBranch $branch
     */
    public function removeBranch(\AppBundle\Entity\UniversityBranch $branch)
    {
        $this->branches->removeElement($branch);
    }

    /**
     * Get branches
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBranches()
    {
        return $this->branches;
    }

    /**
     * Add partner
     *
     * @param \AppBundle\Entity\Partner $partner
     *
     * @return University
     */
    public function addPartner(\AppBundle\Entity\Partner $partner)
    {
        $this->partners[] = $partner;

        return $this;
    }

    /**
     * Remove partner
     *
     * @param \AppBundle\Entity\Partner $partner
     */
    public function removePartner(\AppBundle\Entity\Partner $partner)
    {
        $this->partners->removeElement($partner);
    }

    /**
     * Get partners
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPartners()
    {
        return $this->partners;
    }

    public function getRussianPartners()
    {
        return $this->partners->filter(function($entry) {
            return ! $entry->isForeign();
        });
    }

    public function getForeignPartners()
    {
        return $this->partners->filter(function($entry) {
            return $entry->isForeign();
        });
    }

    /**
     * Set sliderData
     *
     * @param \AppBundle\Entity\SliderData $sliderData
     *
     * @return University
     */
    public function setSliderData(\AppBundle\Entity\SliderData $sliderData = null)
    {
        $this->sliderData = $sliderData;

        return $this;
    }

    /**
     * Get sliderData
     *
     * @return \AppBundle\Entity\SliderData
     */
    public function getSliderData()
    {
        return $this->sliderData;
    }

    /**
     * Set socialLinks
     *
     * @param \AppBundle\Entity\SocialLinks $socialLinks
     *
     * @return University
     */
    public function setSocialLinks(\AppBundle\Entity\SocialLinks $socialLinks = null)
    {
        $this->socialLinks = $socialLinks;

        return $this;
    }

    /**
     * Get socialLinks
     *
     * @return \AppBundle\Entity\SocialLinks
     */
    public function getSocialLinks()
    {
        return $this->socialLinks;
    }

    /**
     * Set locationPoint
     *
     * @param Point $locationPoint
     *
     * @return University
     */
    public function setLocationPoint($locationPoint)
    {
        $this->locationPoint = $locationPoint;

        return $this;
    }

    /**
     * Get locationPoint
     *
     * @return Point
     */
    public function getLocationPoint()
    {
        return $this->locationPoint;
    }

    /**
     * Set photo
     *
     * @param string $photo
     *
     * @return University
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Get photo
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }


}

src/AppBundle/Form/University/SliderDataType.php
<?php

namespace AppBundle\Form\University;

use AppBundle\Entity\SliderData;
use Symfony\Component\Form\{AbstractType, FormBuilderInterface};
use Symfony\Component\OptionsResolver\OptionsResolver;

class SliderDataType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('students')
            ->add('staff')
            ->add('foreignStudents')
            ->add('educationPrograms')
            ->add('eduProgramsForeign')
            ->add('internationalLaboratories');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SliderData::class,
        ]);
    }
}

src/AppBundle/Form/University/SocialLinksType.php
<?php

namespace AppBundle\Form\University;

use AppBundle\Entity\SocialLinks;
use Symfony\Component\Form\{AbstractType, FormBuilderInterface};
use Symfony\Component\OptionsResolver\OptionsResolver;

class SocialLinksType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('vkontakte', null, ['required' => false])
            ->add('instagram', null, ['required' => false])
            ->add('facebook', null, ['required' => false])
            ->add('twitter', null, ['required' => false])
            ->add('youtube', null, ['required' => false])
            ->add('telegram', null, ['required' => false]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SocialLinks::class,
        ]);
    }
}

src/AppBundle/Form/University/UniversityBranchType.php
<?php

namespace AppBundle\Form\University;

use A2lix\TranslationFormBundle\Form\Type\TranslationsType;
use AppBundle\Form\Common\RelatedWithDynamicLoadedCitiesType;
use Tetranz\Select2EntityBundle\Form\Type\Select2EntityType;
use AppBundle\Entity\{City, UniversityBranch};
use Symfony\Component\Form\{AbstractType, FormBuilderInterface};
use Symfony\Component\OptionsResolver\OptionsResolver;

class UniversityBranchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('translations', TranslationsType::class, [
            'translation_domain' => 'dictionary',
            'label' => false,
            'fields' => [
                'address' => [],
                'url' => [
                    'label' => 'university_branch.official_site',
                    'translation_domain' => 'messages'
                ],
                'referencePhone' => [
                    'locale_options' => [
                        'ru' => ['attr' => ['custom-phone-mask-input' => 'on']],
                        'en' => ['attr' => ['custom-phone-mask-input' => 'on']],
                    ]
                ],
                'referenceMail' => [],
                'selectionCommitteePhone' => [
                    'locale_options' => [
                        'ru' => ['attr' => ['custom-phone-mask-input' => 'on']],
                        'en' => ['attr' => ['custom-phone-mask-input' => 'on']],
                    ]
                ],
                'selectionCommitteeMail' => [],
            ],
        ])
        ->add('city', RelatedWithDynamicLoadedCitiesType::class, [
            'required' => true,
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UniversityBranch::class,
            'label' => false,
            'locale' => 'ru',
        ]);
    }
}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\KnowledgeArea;
use AppBundle\Entity\KnowledgeAreaItem;
use AppBundle\Entity\AcademicMobility;
use AppBundle\Entity\News;
use AppBundle\Entity\NewsType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{

    /**
     * @Route(
     *     path="/{_locale}/",
     *     name="homepage",
     *     requirements={"_locale": "%route.available_locales%"}
     * )
     * @Template("@App/default/MainPage/index.html.twig")
     */
    public function mainAction(Request $request)
    {
        $universities = $this->getDoctrine()->getRepository('AppBundle:University')->findForSlider();
        shuffle($universities);

        // Knowledge area repositories
        $knowledgeAreaRepository = $this->getDoctrine()->getRepository(KnowledgeArea::class);
        $knowledgeAreaItemRep = $this->getDoctrine()->getRepository(KnowledgeAreaItem::class);

        $locale = $request->getLocale();
        // Programs
        $knowledgeAreaItemData = $knowledgeAreaItemRep->getFastFiltersData($locale);
        $knowledgeAreaData = $knowledgeAreaRepository->getFastFiltersData($locale);

        // Project and contest
        $knowledgeAreaContestData = $knowledgeAreaRepository->getContestFastFiltersData($locale);
        $knowledgeAreaItemContestData = $knowledgeAreaItemRep->getContestFastFiltersData($locale);

        // Academic mobility
        $knowledgeAreaAcademicData = $knowledgeAreaRepository->getAcademicFastFiltersData($locale);
        $knowledgeAreaItemAcademicData = $knowledgeAreaItemRep->getAcademicFastFiltersData($locale);

        return [
            'universities' => $universities,
            'knowledgeAreaData' => $knowledgeAreaData,
            'knowledgeAreaItemData' => $knowledgeAreaItemData,
            'knowledgeAreaContestData' => $knowledgeAreaContestData,
            'knowledgeAreaItemContestData' => $knowledgeAreaItemContestData,
            'knowledgeAreaAcademicData' => $knowledgeAreaAcademicData,
            'knowledgeAreaItemAcademicData' => $knowledgeAreaItemAcademicData,
        ];
    }

    /**
     * @Template("@App/Default/newsAndEvents.html.twig")
     */
    public function newsAndEventsAction(Request $request, $section = 'all')
    {

        $newsRepository = $this->getDoctrine()->getRepository(News::class);
        $academicMobilityRepository = $this->getDoctrine()
            ->getRepository(AcademicMobility::class);

        $newsUniversity = $newsRepository
            ->findLastNewsForMain(NewsType::UNIVERSITY_NEWS, $request->getLocale());
        $newsAssociations = $newsRepository
            ->findLastNewsForMain(NewsType::ASSOCIATION_NEWS, $request->getLocale());

        $academicMobilities = $academicMobilityRepository
            ->getLastAcademicMobilityForMain(AcademicMobility::ACADEMIC_MOBILITY_EVENT_TYPES, $request->getLocale());

        return [
            'newsUniversity' => $newsUniversity,
            'newsAssociations' => $newsAssociations,
            'academicMobilities' => $academicMobilities,
        ];
    }

}

src/AppBundle/Controller/Home/UniversityController.php
<?php

namespace AppBundle\Controller\Home;

use AppBundle\Configuration\Statistic;
use AppBundle\Entity\News;
use AppBundle\Entity\NewsType;
use AppBundle\Entity\University;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

class UniversityController extends Controller
{
    /**
     * @param Request    $request
     * @param University $university
     *
     * @return array
     * @Route(
     *     path="/{_locale}/university/{id}",
     *     name="home.university.index",
     *     requirements={"_locale": "%route.available_locales%"}
     *     )
     * @Template("AppBundle:default/University:index.html.twig")
     * @Statistic("university")
     */
    public function indexAction(Request $request, University $university)
    {
        $newsRepository = $this->getDoctrine()->getRepository(News::class);
        $universityRepository = $this->getDoctrine()->getRepository(University::class);

        $news = $newsRepository->findLastNewsForUniversity($university, NewsType::UNIVERSITY_NEWS, $request->getLocale());

        $counters = $universityRepository->getCountersByUniversity($university->getId());

        return [
            'counters' => $counters[0],
            'university' => $university,
            'news' => $news,
        ];
    }

    // add here other actions for university page, i.e. programList, contestList, mobilityList, partners
}

src/AppBundle/Resources/views/default/University/index.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block header %}
    {% include "AppBundle::header.html.twig" %}
{% endblock %}

{% block body_class %}university-page{% endblock %}

{% block footer %}
    {% include 'AppBundle::footer.html.twig' %}
{% endblock %}

{% block body %}
    <main>
        <section class="university-heading">
            {# Insert image for university page from university.backgroundImage #}
            <img src="{{ asset('bundles/app/css/img/university/page/' ~ university.photo) }}" alt=""/>
            <div class="container">
                <h1 class="default-title">
                    {{ university.translate().getName() }}
                </h1>
            </div>
        </section>
        <section class="content">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                        {% if university.mainBranch %}
                            {% include '@App/default/University/main_branch.html.twig' with {'mainBranch': university.mainBranch} %}
                        {% endif %}
                        {% if university.subBranches %}
                            {% include '@App/default/University/sub_branches.html.twig' with {'subBranches': university.subBranches} %}
                        {% endif %}
                        {% if university.socialLinks %}
                            {% include '@App/default/University/social_links.html.twig'
                            with {'socialLinks': university.socialLinks} %}
                        {% endif %}
                    </div>
                    <div class="col-sm-7 about-info">
                        <div class="content-info">
                            <ol class="breadcrumb">
                                <li><a href="{{ path('homepage') }}">{{ 'main'|trans }}</a></li>
                                <li><a href="{{ path('main.static.members') }}">{{ 'middle-menu.association-members'|trans }}</a></li>
                            </ol>
                        </div>
                        {% if university.sliderData %}
                            {% include '@App/default/University/slider_data.html.twig' with {'sliderData': university.sliderData} %}
                        {% endif %}

                            {{ university.translate().getDescription() | nl2br }}

                        {% if university.translate().promoVideo %}
                            <div class="promo-video-frame">
                                {{ university.translate().promoVideo |raw }}
                            </div>
                        {% endif %}
                        {% for document in university.uploadedDocuments %}
                            <a href="{{ path('download.document', {id:document.id}) }}" class="download-link">{{ document.viewName }}<span>{{ document.getFormattedBytes() }}</span></a>
                        {% endfor %}
                    </div>
                    {% include '@App/default/University/news.html.twig' %}
                </div>
                <div class="clearfix row rubrics aligned-center">
                    <div class="col-md-3">
                        <a href="{{ path('main.program.list', {'university':[university.id] }) }}" class="rubrics-item">
                            <span class="rubric-counter">{{ counters['programCount'] }}</span>
                            <p>
                                <span class="rubric-title">
                                  {{ 'profile_main.edu_programms.title' | trans }}
                               </span>
                            </p>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="{{ path('main.contest.list', {'university':[university.id]}) }}" class="rubrics-item">
                            <span class="rubric-counter">{{ counters['contestCount'] }}</span>
                            <p>
                                <span class="rubric-title">
                                  {{ 'profile_main.projects.title' | trans }}
                               </span>
                            </p>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="{{ path('main.academic_mobility.list', {'university':[university.id]}) }}" class="rubrics-item">
                            <span class="rubric-counter">{{ counters['academicCount'] }}</span>
                            <p>
                                <span class="rubric-title">
                                  {{ 'profile_menu.academic_mobility.title' | trans }}
                               </span>
                            </p>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="{{ path('main.practice.list', {'university':[university.id]}) }}" class="rubrics-item">
                            <span class="rubric-counter">{{ counters['bestCount'] }}</span>
                            <p>
                                <span class="rubric-title">
                                  {{ 'profile_main.best_pract.title' | trans }}
                               </span>
                            </p>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

src/AppBundle/Resources/views/default/University/main_branch.html.twig
{{ uni_logo(mainBranch.university) }}

<div class="about-contacts">

    <p>{{ mainBranch.city }}, {{ mainBranch.translate().getAddress() }}</p>
    <a href="http://maps.google.com/?q={{ mainBranch.city }}, {{ mainBranch.translate().getAddress() }}"
       class="university-map-link" target="_blank">{{ 'show_on_map'|trans }}</a>
    {% if (mainBranch.translate().getUrl()) %}
        <div class="contacts-item">
            <p class="medium about-sub-title">{{ 'university_branch.official_site' | trans }}</p>
            <a href="{{ redirectLink(mainBranch) }}"
                    {% set url = mainBranch.translate().getUrl()|replace({'http://': "", "www." : "", "https://" : ""}) %}
                    {% if url|length > 8 %}
                        {% set url = url|e('url')|split('%')[0] %}
                    {% endif %}
               target="_blank"
               class="university-link">{{ url }}<i
                        class="fa fa-external-link" aria-hidden="true"></i></a>
        </div>
    {% endif %}
       {% if (mainBranch.translate().getReferencePhone()) %}
        <div class="contacts-item">
            <p class="medium about-sub-title">{{ 'reference' | trans }}</p>
            {{ mainBranch.translate().getReferencePhone() }}
            <a href="mailto:{{ mainBranch.translate().getReferenceMail() }}"
               class="highlighted">{{ mainBranch.translate().getReferenceMail() }}</a>
        </div>
        {% endif %}
        {% if (mainBranch.translate().getSelectionCommitteePhone()) %}
        <div class="contacts-item">
            <p class="medium about-sub-title">{{ 'selection' | trans }}</p>
            {{ mainBranch.translate().getSelectionCommitteePhone() }}
            <a href="mailto:{{ mainBranch.translate().getSelectionCommitteeMail() }}"
               class="highlighted">{{ mainBranch.translate().getSelectionCommitteeMail() }}</a>
        </div>
        {% endif %}
        {#{% if (mainBranch.getWorkingHours()) %}#}
        {#<div class="contacts-item">#}
            {#<p class="medium about-sub-title">{{ 'Working hours' | trans }}</p>#}
            {#{{ mainBranch.getWorkingHours() }}#}
            {# Время выводится только относительно Москвы, не хватает определения пояса по городу и стране#}
            {#{% set currentTimezone = date("Europe/Moscow") %}#}
            {#{% set utc = currentTimezone.diff(date("Atlantic/Reykjavik")) %}#}
            {#{% set msk = currentTimezone.diff(date("Europe/Moscow")) %}#}
            {#<p>#}
                {#{{ mainBranch.city }}<br> MSK+{{ msk|date('%h') }} (UTC+{{ utc|date('%h') }})#}
            {#</p>#}
        {#</div>#}
        {#{%  endif %}#}
</div>

src/AppBundle/Resources/views/default/University/news.html.twig
{% if news is defined  and news|length > 0 %}
    <div class="col-sm-3">
        <ul class="nav nav-tabs main-nav news-nav">
            <li class="active">
                <a href="{{ path('main.news.search', {'universities[]': university.id }) }}">
                    {{ 'news_of_university' | trans }}
                </a>
            </li>
        </ul>
        <div class="border-wrapper clearfix">
            {% for uNews in news %}
                <article class="news-preview">
                    <p class="default-label">
                        <a href="{{ path('home.university.index',{'id': university.id }) }}" class="pink">{{ uNews.university.translate().shortName }}</a>
                        <a href="{{ path('main.news.search',{'rubrics':[uNews.rubric.id]}) }}">{{ uNews.rubric | trans([], 'dictionary') }}</a>
                    </p>
                    <h1>
                        <a href="{{ path('main.news.show', {id: uNews.id}) }}">{{ uNews.translate().title }}</a>
                    </h1>
                </article>
            {% endfor %}
        </div>
    </div>
{% endif %}

src/AppBundle/Resources/views/default/University/slider_data.html.twig
<div class="row about-numbers">
    <div class="col-sm-4">
        <p class="about-title">
            {{ sliderData.educationPrograms }}
        </p>
        <p class="about-info">
            {{ 'slider_programs' | trans }}
        </p>
    </div>
    <div class="col-sm-4">
        <p class="about-title">
            {{ sliderData.students }}
        </p>
        <p class="about-info">
            {{ 'slider_students' | trans }}
        </p>
    </div>
    <div class="col-sm-4">
        <p class="about-title">
            {{ sliderData.staff }}
        </p>
        <p class="about-info">
            {{ 'slider_staff' | trans }}
        </p>
    </div>
    <div class="col-sm-4">
        <p class="about-title">
            {{ sliderData.eduProgramsForeign }}
        </p>
        <p class="about-info">
            {{ 'slider_foreign_programs' | trans }}
        </p>
    </div>
    <div class="col-sm-4">
        <p class="about-title">
            {{ sliderData.foreignStudents }}
        </p>
        <p class="about-info">
            {{ 'slider_foreign_students' | trans }}
        </p>
    </div>
    <div class="col-sm-4">
        <p class="about-title">
            {{ sliderData.internationalLaboratories }}
        </p>
        <p class="about-info">
            {{ 'slider_laboratories' | trans }}
        </p>
    </div>
</div>

src/AppBundle/Resources/views/default/University/social_links.html.twig
<div class="about-social-links">
    <p class="about-sub-title">{{ 'in_touch' | trans }}</p>

    {% if socialLinks.vkontakte %}
        <a href="{{ socialLinks.vkontakte }}" class="social" target="_blank">
            <i class="fa fa-vk" aria-hidden="true"></i></a>
    {% endif %}

    {% if socialLinks.facebook %}
        <a href="{{ socialLinks.facebook }}" class="social" target="_blank">
            <i class="fa fa-facebook" aria-hidden="true"></i></a>
    {% endif %}

    {% if socialLinks.instagram %}
        <a href="{{ socialLinks.instagram }}" class="social" target="_blank">
            <i class="fa fa-instagram" aria-hidden="true"></i></a>
    {% endif %}

    {% if socialLinks.twitter %}
        <a href="{{ socialLinks.twitter }}" class="social" target="_blank">
            <i class="fa fa-twitter" aria-hidden="true"></i></a>
    {% endif %}

    {% if socialLinks.youtube %}
        <a href="{{ socialLinks.youtube }}" class="social" target="_blank">
            <i class="fa fa-youtube" aria-hidden="true"></i></a>
    {% endif %}

    {% if socialLinks.telegram %}
        <a href="{{ socialLinks.telegram }}" class="social" target="_blank">
            <i class="fa fa-telegram" aria-hidden="true"></i></a>
    {% endif %}

</div>

src/AppBundle/Resources/views/default/University/sub_branches.html.twig
{% for subBranch in subBranches %}
    <div class="content-toggle toggle">
        <input type="hidden" id="lang_key" value="{{ app.request.locale }}">

        {# Toggler header #}
        <label class="control-label">{{ 'branch' | trans }} {{ subBranch.city }}</label>

        {# Toggled content #}
        <div class="content-toggle-item">

            {# Contacts block #}
            <div class="about-contacts">
                <p>{{ subBranch.city }}, {{ subBranch.translate().getAddress() }}</p>
                <a href="http://maps.google.com/?q={{ subBranch.city }}, {{ subBranch.translate().getAddress() }}"
                   class="university-map-link"
                   target="_blank">Посмотреть на карте</a>

                <div class="clearfix">
                    <div class="contacts-item">
                        <p class="medium about-sub-title">{{ 'reference' | trans }}</p>
                        {{ subBranch.translate().getReferencePhone() }}
                        <a href="mailto:{{ subBranch.translate().getReferenceMail() }}"
                           class="highlighted">{{ subBranch.translate().getReferenceMail() }}</a>
                    </div>

                    <div class="contacts-item">
                        <p class="medium about-sub-title">{{ 'selection' | trans }}</p>
                        {{ subBranch.translate().getSelectionCommitteePhone() }}
                        <a href="mailto:{{ subBranch.translate().getSelectionCommitteeMail() }}"
                           class="highlighted">{{ subBranch.translate().getSelectionCommitteeMail() }}</a>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>

        </div>
    </div>
{% endfor %}